export default {
  // generators
  componentMessage: 'This component is generated by the generator',
  welcome: 'Welcome to use generator to generate your file',

  // LoginScene
  loginScene: 'Login',
  submit: 'Submit',
  placeholderEmail: 'Please enter your email',
  placeholderPassword: 'Please enter your password',
  email: 'Email',
  password: 'Password',

  // HomeScene
  homeScene: 'Home Scene',
  login: 'Go to Login!',
  vi: 'Vietnamese',
  en: 'English',
  add: 'Add',
  minus: 'Minus',

  // AppFooter
  footer: 'react-native-boilerplate',

  // AppHeader
  back: 'Back',

  // Validate Message
  required: 'This is a required field',
  isEmail: 'Incorrect email format',
  minLength: 'Minimum of',
  characters: 'characters',
  confirmation: 'Password and password confirmation must be the same',
};
